#!/bin/sh

# Regenerate the loadable plugin jars used by TestPluginManager.
# There are three plugin project trees: test/testplugins/v{1,2,3} .
# This must be run if the plugins are changed or the keystores regenerated.

proj_dir=`pwd`
plugin_projs="v1 v2 v3"

err_exit() {
  echo "$*" >&2
  exit 1
}

for x in ${plugin_projs}; do
  echo $x
  ( cd test/testplugins/${x}
    echo `pwd` mvn $@
    mvn clean package -Dkeystore.file="${proj_dir}/src/test/java/org/lockss/test/goodguy.keystore" -Dkeystore.alias=goodguy -Dkeystore.password=f00bar  $@
      cp target/pluginjars/*.jar "${proj_dir}/src/test/java/org/lockss/test/mock-plugin-${x}.jar"
  ) || err_exit "Plugin packaging failure"

done
