#!/bin/bash

if [ "$#" == "0" ]; then
 echo "Usage: $0 <java-args> <class-name> <args>"
 echo "Runs <class-name> "
 echo "Must be run from project base dir."
 exit 1
fi

PROJECT_DIR=.

CLASSPATH=`cat target/test-classpath`
export CLASSPATH

args=""
quiet=""

while true ; do
  case "$1" in
    "-q" )
      quiet=1  
      shift; continue;;
    "-classpath" )
      if [ -z "$CLASSPATH" ] ; then
	CLASSPATH="$2"
      else
	CLASSPATH="$CLASSPATH":"$2"
      fi
      [ -z "$quiet" ] && echo "CLASSPATH=$CLASSPATH"
      shift; shift; continue;;
    "-11" )
      if [ -z "$JAVA_11_HOME" ] ; then
	echo "-11 option requires JAVA_11_HOME to point to jave 11 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_11_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-17" )
      if [ -z "$JAVA_17_HOME" ] ; then
	echo "-17 option requires JAVA_17_HOME to point to 17 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_17_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-8" )
      if [ -z "$JAVA_8_HOME" ] ; then
	echo "-8 option requires JAVA_8_HOME to point to 8 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_8_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-*" )
      args="$args $1"
      shift; continue;;
  esac
  break;
done

class=$1
shift

java $args $class "$@"
